---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - loki_url is defined
      - host_port is defined
      - dashy_config_path is defined

- name: Create the config directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}dashy"
    state: directory
    mode: "0755"

- name: Copy dashy config
  copy:
    src: "{{ dashy_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}dashy/conf.yml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    pull: true
    cleanup: true
    image: "lissy93/{{ application_name }}:3.0.1"
    restart_policy: "always"
    log_driver: "loki"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}dashy/conf.yml:/app/user-data/conf.yml"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    exposed_ports:
      - "8080"
    published_ports:
      - "0.0.0.0:{{ host_port }}:8080"
