---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - encryption_key_path is defined
      - aws_access_key_id is defined
      - aws_secret_access_key is defined

- name: Add the backup GPG key
  copy:
    src: "{{ encryption_key_path }}"
    dest: /tmp/backup.asc
    owner: root
    group: root
    mode: "0600"

- name: Import the backup GPG key
  command: gpg --import /tmp/backup.asc
  changed_when: false

- name: Create the aws config folder
  file:
    path: "/root/.aws"
    state: directory
    mode: "0700"

- name: Copy aws config
  template:
    src: awsconfig.j2
    dest: "/root/.aws/config"
    owner: root
    group: root
    mode: "600"

- name: Copy aws credentials
  template:
    src: credentials.j2
    dest: "/root/.aws/credentials"
    owner: root
    group: root
    mode: "600"
