---
- name: Install common system packages
  import_tasks: install-system-packages.yml

- name: Install AWS Client
  import_tasks: install-aws-cli.yml

- name: Install docker
  import_tasks: install-docker.yml

- name: Provide aws creds to docker
  import_tasks: provide-aws-creds-to-docker.yml

- name: Install backup script capabilities
  import_tasks: install-backup-script.yml

- name: Install docker loki plugin
  import_tasks: install-loki-plugin.yml
  when: ansible_architecture == "x86_64"

- name: Install docker loki plugin (ARM)
  import_tasks: install-loki-plugin-arm.yml
  when: ansible_architecture == "armv7l"
