repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.0
    hooks:
      - id: ansible-lint
  - repo: local
    hooks:
      - id: trivy-image-scan
        name: Trivy Image Scanner
        entry: ./pre-commit/security_scanner
        language: script
        pass_filenames: false
        files: '\/tasks\/main\.yml$'
        always_run: true
