namespace: namelivia
name: monorepo
version: 2.326.2
readme: README.md
authors:
  - José Ignacio Amelivia Santiago <hello@namelivia.com>
description: Monorepo for all the Ansible roles for my personal infrastructure
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - infrastructure
  - ansible
dependencies:
  community.docker: '>=4.5.0'
  ansible.posix: '>=1.6.0'
  prometheus.prometheus: '>=0.26.0'
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
