---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - alloy_host is defined
      - notifications_service_endpoint is defined
      - notifications_service_network_name is defined
      - docker_network_name is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "namelivia/recipe-suggestions:latest"
    pull: true
    cleanup: true
    memory: "200MB"
    log_driver: "loki"
    log_options:
      loki-url: "{{ alloy_host }}"
      loki-batch-size: "400"
    networks:
      - name: "{{ docker_network_name }}"
      - name: "{{ notifications_service_network_name }}"
    env:
      NOTIFICATIONS_SERVICE_ENDPOINT: "{{ notifications_service_endpoint }}"
