---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - host_port is defined
      - docker_network_name is defined
      - alloy_host is defined
      - prometheus_config_path is defined
      - uid
      - gid

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create the files directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Create the data directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"


- name: Copy prometheus config
  copy:
    src: "{{ prometheus_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/config.yml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "prom/prometheus:v3.2.1"
    restart_policy: "always"
    cleanup: true
    user: "{{ uid }}:{{ gid }}"
    exposed_ports:
      - "9090"
    published_ports:
      - "0.0.0.0:{{ host_port }}:9090"
    networks:
      - name: "{{ docker_network_name }}"
    log_driver: "syslog"
    log_options:
      loki-url: "{{ alloy_host }}"
      loki-batch-size: "400"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data:/prometheus"
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/config.yml:/etc/prometheus/prometheus.yml"

# Restart the app container, sometimes needed for upgrades
- name: Restart prometheus
  command: docker restart prometheus
  register: restart_prometheus_result
  changed_when: restart_prometheus_result.rc != 0
