galaxy_info:
  role_name: garments_server
  author: José Ignacio Amelivia Santiago <hello@namelivia.com>
  description: Ansible role I use to install and configure namelivia/garments-server
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
