galaxy_info:
  role_name: common
  namespace: namelivia
  author: José Ignacio Amelivia Santiago <jignacio.amelivia@gmail.com>
  description: Ansible role with common operations for all instances
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
