---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - backups_notifications_endpoint is defined
      - backup_day is defined
      - gpg_recipient is defined

- name: Create the backup directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/backup"
    state: directory
    mode: "0700"

- name: Create the backupscript
  template:
    src: files_backup.j2
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/backup.sh"
    owner: root
    group: root
    mode: "0755"

- name: Create a backup every week
  cron:
    name: "backup {{ application_name }} files"
    weekday: "{{ backup_day }}"
    minute: "0"
    hour: "6"
    job: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/backup.sh"
    user: root

- name: Create the restore script
  template:
    src: restore_files.j2
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/restore_files.sh"
    owner: root
    group: root
    mode: "0755"
