---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - alloy_host is defined
      - radarr_downloads_folder is defined
      - radarr_movies_folder is defined
      - backup_day is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create the config directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/config"
    state: directory
    mode: "0755"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}-app"
    image: "linuxserver/radarr:6.0.3-nightly"
    restart_policy: "always"
    pull: true
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      tag: "{{ application_name }}-app"
      syslog-format: "rfc5424"
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - 7878:7878
    volumes:
      - "{{ radarr_downloads_folder }}:/downloads"
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/config:/config"
      - "{{ radarr_movies_folder }}:/movies"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Madrid"

- name: Setup file backups
  include_role:
    name: ansible-backups
    tasks_from: setup-file-backups

- name: Setup S3 backups
  include_role:
    name: ansible-backups
    tasks_from: setup-s3-backups

- name: Setup restic backups
  include_role:
    name: ansible-backups
    tasks_from: setup-restic-backups
  vars:
    file_path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/config"
