---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - exposed_ports is defined

- name: "Remove RETURN rule from DOCKER-USER chain"
  ansible.builtin.command: iptables -D DOCKER-USER -j RETURN
  failed_when: "'No chain/target/match by that name' not in result.stderr"
  changed_when: "'No chain/target/match by that name' not in result.stderr"


- name: "Allow port for VPN addresses only"
  ansible.builtin.iptables:
    action: "insert"
    chain: DOCKER-USER
    protocol: tcp
    source_port: "{{ item }}"
    src_range: 192.168.254.1-192.168.254.255
    jump: ACCEPT
  with_items: "{{ exposed_ports }}"

- name: "Disallow port for other addresses"
  ansible.builtin.iptables:
    chain: DOCKER-USER
    source_port: "{{ item }}"
    protocol: tcp
    jump: DROP
  with_items: "{{ exposed_ports }}"

- name: "Re-add RETURN rule to the end of the DOCKER-USER chain"
  ansible.builtin.iptables:
    chain: DOCKER-USER
    jump: RETURN
    action: "append"
