---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - exposed_ports is defined

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'iptables-persistent'

- name: "Flush the DOCKER-USER chain in the iptables firewall"
  ansible.builtin.iptables:
    chain: DOCKER-USER
    flush: true

- name: "Allow port for VPN addresses only"
  ansible.builtin.iptables:
    action: "insert"
    chain: DOCKER-USER
    protocol: tcp
    in_interface: eth0
    destination_port: "{{ item }}"
    source: '!192.168.254.0/24'
    jump: DROP
  with_items: "{{ exposed_ports }}"

- name: "Add rule to allow traffic to the exposed ports"
  ansible.builtin.iptables:
    action: "insert"
    chain: DOCKER-USER
    jump: RETURN

- name: "Save current state of the firewall in system file"
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4
