---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - exposed_ports is defined

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'iptables-persistent'

# TODO: This could be more configurable
- name: "Allow node exporter port for VPN addresses only"
  ansible.builtin.iptables:
    action: "insert"
    chain: INPUT
    protocol: tcp
    in_interface: eth0
    destination_port: "9100"
    source: '!192.168.254.0/24'
    jump: DROP

- name: "Allow port for VPN addresses only"
  ansible.builtin.iptables:
    action: "insert"
    chain: DOCKER-USER
    protocol: tcp
    in_interface: eth0
    destination_port: "{{ item }}"
    source: '!192.168.254.0/24'
    jump: DROP
  with_items: "{{ exposed_ports }}"

- name: "Save current state of the firewall in system file"
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4
