---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - exposed_ports is defined

- name: "Allow port for VPN addresses only"
  ansible.builtin.iptables:
    action: "insert"
    chain: DOCKER-USER
    protocol: all
    in_interface: eth0
    destination_port: "{{ item }}"
    source: '!192.168.254.0/24'
    jump: DROP
  with_items: "{{ exposed_ports }}"
