---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - alloy_host is defined
      - consumer_key is defined
      - consumer_secret is defined
      - access_token_key is defined
      - access_token_secret is defined
      - search_string is defined
      - chance_to_act is defined
      - chance_to_favorite is defined
      - chance_to_follow is defined
      - language is defined
      - idle_period is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "namelivia/like-and-share-twitter-bot:latest"
    restart_policy: "always"
    pull: true
    cleanup: true
    memory: "50MB"
    networks:
      - name: "{{ docker_network_name }}"
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      loki-batch-size: "400"
    env:
      CONSUMER_KEY: "{{ consumer_key }}"
      CONSUMER_SECRET: "{{ consumer_secret }}"
      ACCESS_TOKEN_KEY: "{{ access_token_key }}"
      ACCESS_TOKEN_SECRET: "{{ access_token_secret }}"
      SEARCH_STRING: "{{ search_string }}"
      CHANCE_TO_ACT: "{{ chance_to_act }}"
      CHANCE_TO_FAVORITE: "{{ chance_to_favorite }}"
      CHANCE_TO_FOLLOW: "{{ chance_to_follow }}"
      LANGUAGE: "{{ language }}"
      IDLE_PERIOD: "{{ idle_period }}"
