---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - docker_network_subnet is defined
      - host_port is defined
      - alloy_host is defined
      - dump_day is defined
      - backup_day is defined
      - trusted_domains is defined
      - admin_user is defined
      - admin_password is defined
      - database_container_name is defined
      - database_user is defined
      - database_password is defined
      - user is defined
      - group is defined
      - uid is defined
      - gid is defined
      - database_name is defined
      - database_network_name is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"

- name: Create the nextcloud data volumne
  community.docker.docker_volume:
    name: nextcloud-data

- name: Create the files directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create the data directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create the config directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/config"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create database
  include_role:
    name: ansible-postgres
    tasks_from: create-postgres-database-if-not-exists

- name: Create app container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "nextcloud:31.0.8"
    pull: true
    cleanup: true
    user: "{{ uid }}:{{ gid }}"
    restart_policy: "always"
    exposed_ports:
      - "80"
    published_ports:
      - "0.0.0.0:{{ host_port }}:80"
    networks:
      - name: "{{ docker_network_name }}"
      - name: "{{ database_network_name }}"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/config:/var/www/html/config"
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data:/var/www/html/data"
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      tag: "{{ application_name }}"
      syslog-format: "rfc5424"
    env:
      POSTGRES_DB: "{{ database_name }}"
      POSTGRES_USER: "{{ database_user }}"
      POSTGRES_PASSWORD: "{{ database_password }}"
      POSTGRES_HOST: "{{ database_container_name }}"
      NEXTCLOUD_ADMIN_USER: "{{ admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ trusted_domains }}"

- name: Run occ upgrade
  command: docker exec -u {{ uid }}:{{ gid }} {{ app_container_name }} ./occ upgrade
  register: result
  failed_when: result.rc != 0 and "No upgrade required" not in result.stdout
  changed_when: "'No upgrade required' not in result.stdout"

- name: Install the calendar app
  command: docker exec -u {{ uid }}:{{ gid }} {{ app_container_name }} ./occ app:install calendar
  register: result
  failed_when: result.rc != 0 and "already installed" not in result.stdout
  changed_when: "'already installed' not in result.stdout"

- name: Install the tasks app
  command: docker exec -u {{ uid }}:{{ gid }} {{ app_container_name }} ./occ app:install tasks
  register: result
  failed_when: result.rc != 0 and "already installed" not in result.stdout
  changed_when: "'already installed' not in result.stdout"

- name: Setup file backups
  include_role:
    name: ansible-backups
    tasks_from: setup-file-backups

- name: Setup S3 backups
  include_role:
    name: ansible-backups
    tasks_from: setup-s3-backups
