---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - alloy_host is defined
      - database_url is defined
      - jwk_endpoint is defined
      - database_container_name is defined
      - database_user is defined
      - database_password is defined
      - docker_network_name is defined
      - docker_network_subnet is defined
      - database_network_name is defined
      - dump_day is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "namelivia/user-info-service:latest"
    memory: "200MB"
    pull: true
    restart_policy: "always"
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      syslog-format: "rfc5424"
    networks:
      - name: "{{ docker_network_name }}"
      - name: "{{ database_network_name }}"
    exposed_ports:
      - "80"
    env:
      DATABASE_URL: "{{ database_url }}"
      JWK_ENDPOINT: "{{ jwk_endpoint }}"

- name: Create database
  include_role:
    name: ansible-postgres
    tasks_from: create-postgres-database-if-not-exists

- name: Upgrade alembic
  include_role:
    name: ansible-fastapi
    tasks_from: upgrade-alembic

- name: Setup database backups
  include_role:
    name: ansible-backups
    tasks_from: setup-postgres-database-backups

- name: Setup S3 backups
  include_role:
    name: ansible-backups
    tasks_from: setup-s3-backups
