---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - loki_url is defined
      - garments_api_endpoint is defined
      - host_port is defined
      - docker_network_name is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    pull: true
    cleanup: true
    image: "namelivia/garments-client:1.7.2"
    memory: "10MB"
    restart_policy: "always"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    exposed_ports:
      - "80"
    published_ports:
      - "0.0.0.0:{{ host_port }}:80"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      VUE_APP_API_ENDPOINT: "{{ garments_api_endpoint }}"
