---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - aws_access_key_id is defined
      - aws_secret_access_key is defined

- name: Create the credentials directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Provide aws credentials to the docker daemon
  # notify: Restart and reload docker service
  template:
    src: aws-credentials.j2
    dest: "/etc/systemd/system/docker.service.d/aws-credentials.conf"
    owner: root
    group: root
    mode: "600"
    # register: aws_credentials
