---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - alloy_host is defined
      - host_port is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "namelivia/tombraiderjs:latest"
    pull: true
    cleanup: true
    memory: "10MB"
    restart_policy: "always"
    log_driver: "loki"
    log_options:
      loki-url: "{{ alloy_host }}"
      loki-batch-size: "400"
    networks:
      - name: "{{ docker_network_name }}"
    exposed_ports:
      - "80"
    published_ports:
      - "0.0.0.0:{{ host_port }}:80"
