---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - mastodon_enabled is defined
      - mastodon_client_id is defined
      - mastodon_client_secret is defined
      - mastodon_api_base_url is defined
      - mastodon_login is defined
      - mastodon_password is defined
      - subs_uri is defined
      - subs_encoding is defined
      - video_uri is defined
      - output_uri is defined
      - text_color is defined
      - text_size is defined
      - text_font is defined
      - idle_period is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create the movie directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}/movies"
    state: directory
    mode: "0700"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "namelivia/movie-quote-mastodon-bot:1.0.1"
    pull: true
    cleanup: true
    restart_policy: "always"
    memory: "200MB"
    networks:
      - name: "{{ docker_network_name }}"
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      tag: "{{ application_name }}"
      syslog-format: "rfc5424"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}movies:/movies"
    env:
      MASTODON_ENABLED: "{{ mastodon_enabled }}"
      MASTODON_CLIENT_ID: "{{ mastodon_client_id }}"
      MASTODON_CLIENT_SECRET: "{{ mastodon_client_secret }}"
      MASTODON_API_BASE_URL: "{{ mastodon_api_base_url }}"
      MASTODON_LOGIN: "{{ mastodon_login }}"
      MASTODON_PASSWORD: "{{ mastodon_password }}"
      SUBS_URI: "{{ subs_uri }}"
      SUBS_ENCODING: "{{ subs_encoding }}"
      VIDEO_URI: "{{ video_uri }}"
      OUTPUT_URI: "{{ output_uri }}"
      TEXT_COLOR: "{{ text_color }}"
      TEXT_SIZE: "{{ text_size }}"
      TEXT_FONT: "{{ text_font }}"
      IDLE_PERIOD: "{{ idle_period }}"
