galaxy_info:
  role_name: grafana
  namespace: namelivia
  author: José Ignacio Amelivia Santiago <jignacio.amelivia@gmail.com>
  description: Ansible role I use to install and configure grafana
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
