---
- name: 'Check mandatory variables are defined'
  ansible.builtin.assert:
    that:
      - application_name is defined
      - alloy_host is defined
      - gallery_api_endpoint is defined
      - host_port is defined
      - docker_network_name is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    pull: true
    cleanup: true
    image: "namelivia/gallery-client:latest"
    memory: "10MB"
    restart_policy: "always"
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      syslog-format: "rfc5424"
    exposed_ports:
      - "80"
    published_ports:
      - "0.0.0.0:{{ host_port }}:80"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      VUE_APP_API_ENDPOINT: "{{ gallery_api_endpoint }}"
