galaxy_info:
  namespace: namelivia
  role_name: dashy
  author: José Ignacio Amelivia Santiago <jignacio.amelivia@gmail.com>
  description: Ansible role to install and configure dashy
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
