---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - apprise_config_folder is defined
      - apprise_user is defined
      - apprise_group is defined
      - alloy_host is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Copy apprise config
  copy:
    src: "{{ apprise_config_folder }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}"
    owner: "{{ apprise_user }}"
    group: "{{ apprise_group }}"
    force: true
    mode: "0644"
    directory_mode: "0775"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "caronc/apprise:1.2.0"
    pull: true
    cleanup: true
    networks:
      - name: "{{ docker_network_name }}"
    exposed_ports: 8000
    published_ports:
      - "0.0.0.0:9000:8000"  # map the port to the host's 9000 port
    memory: "400MB"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}:/config"
    log_driver: "loki"
    log_options:
      loki-url: "{{ alloy_host }}"
      loki-batch-size: "400"
    env:
      APPRISE_STATEFUL_MODE: "simple"
