---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - alloy_host is defined
      - metube_downloads_folder is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}-app"
    image: "ghcr.io/alexta69/metube:2025.09.06"
    restart_policy: "always"
    pull: true
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      tag: "{{ application_name }}-app"
      syslog-format: "rfc5424"
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - 8081:8081
    volumes:
      - "{{ metube_downloads_folder }}:/downloads"
