galaxy_info:
  namespace: namelivia
  role_name: miniflux
  author: José Ignacio Amelivia Santiago <jignacio.amelivia@gmail.com>
  description: Ansible role I use to install and configure miniflux
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
