---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - host_port is defined
      - docker_network_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - host_port is defined
      - promtail_config_path is defined
      - promtail_user is defined
      - promtail_group is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Copy config
  copy:
    src: "{{ promtail_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}promtail/config.yaml"
    owner: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
    mode: '0644'

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "grafana/promtail:3.4.3"
    restart_policy: "always"
    cleanup: true
    pull: true
    exposed_ports:
      - 9080
    published_ports:
      - "0.0.0.0:{{ host_port }}:9080"
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}promtail/config.yaml:/etc/promtail/config.yaml"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}-{{ inventory_hostname }}"
