---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - alloy_host is defined
      - host_port is defined
      - backup_day is defined
      - docker_network_name is defined
      - user is defined
      - password is defined
      - uid is defined
      - gid is defined
      - owner is defined
      - group is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create the data directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data"
    state: directory
    mode: "0755"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}-app"
    image: "ghcr.io/luckyturtledev/anki:latest"
    restart_policy: "always"
    cleanup: true
    memory: "100MB"
    networks:
      - name: "{{ docker_network_name }}"
    exposed_ports:
      - "8080"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data:/data"
    env:
      SYNC_USER1: "{{ user }}:{{ password }}"
      RUST_LOG: "info"
    log_driver: "syslog"
    user: "{{ uid }}:{{ gid }}"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      loki-batch-size: "400"
    published_ports:
      - "0.0.0.0:{{ host_port }}:8080"

- name: Setup restic backups
  include_role:
    name: ansible-backups
    tasks_from: setup-restic-backups
  vars:
    file_path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files"
