galaxy_info:
  role_name: like_and_share_twitter_bot
  author: José Ignacio Amelivia Santiago <jignacio.amelivia@gmail.com>
  description: Ansible role I use to install and configure namelivia/like-and-share-twitter-bot
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
