---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - host_port is defined
      - docker_network_name is defined
      - alloy_host is defined

- name: Create the dockernetwork
  community.docker.docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  community.docker.docker_container:
    name: "{{ application_name }}"
    image: "quay.io/keycloak/keycloak:26.2.4"
    restart_policy: "always"
    cleanup: true
    pull: true
    exposed_ports:
      - 8080
    published_ports:
      - "0.0.0.0:{{ host_port }}:8080"
    networks:
      - name: "{{ docker_network_name }}"
    log_driver: "syslog"
    log_options:
      syslog-address: "tcp://{{ alloy_host }}:51893"
      tag: "{{ application_name }}-app"
      syslog-format: "rfc5424"
    command: >-
      start-dev

# Restart keycloack
- name: Restart keycloack
  command: docker restart keycloack
  register: restart_keycloack_result
  changed_when: restart_keycloack_result.rc != 0
